import React, { useState } from 'react';
import { Copy, Check, X, FileText, Download, Share2 } from 'lucide-react';
import { AnalysisResult } from '../types';

interface ExportSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult;
}

export const ExportSummaryModal: React.FC<ExportSummaryModalProps> = ({
  isOpen,
  onClose,
  result,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const markdownText = `# SkillLens Career Skill-Gap Analysis Report
Target Role: ${result.roleTitle}
Skill Match Coverage: ${result.matchPercentage}%
Date: ${new Date().toLocaleDateString()}

## 1. Skill Status Breakdown
- Matched Skills (${result.matchedSkills.length}): ${result.matchedSkills.map(s => s.name).join(', ') || 'None'}
- Developing Skills (${result.developingSkills.length}): ${result.developingSkills.map(s => s.name).join(', ') || 'None'}
- Missing Skills (${result.missingSkills.length}): ${result.missingSkills.map(s => s.name).join(', ') || 'None'}

## 2. Skill Gap Diagnosis
${result.gapExplanation.summary}

Top Foundational Strengths:
${result.gapExplanation.foundationalStrengths.map(s => `- ${s}`).join('\n')}

Priority Competencies to Bridge:
${result.gapExplanation.criticalGaps.map(s => `- ${s}`).join('\n')}

Action Advice:
${result.gapExplanation.actionAdvice}

## 3. Recommended Portfolio Project
Project: ${result.recommendedProject.title}
Difficulty: ${result.recommendedProject.difficulty} (Est. ${result.recommendedProject.estimatedHours})
Why Selected: ${result.recommendedProject.whySelected}

Skills Developed:
${result.recommendedProject.skillsDeveloped.map(s => `- ${s}`).join('\n')}

Recommended Dataset:
${result.recommendedProject.recommendedDataset.name} - ${result.recommendedProject.recommendedDataset.description}

## 4. Learning Roadmap Milestones
${result.learningRoadmap.map(step => `Step ${step.stepNumber} [${step.durationWeeks}]: ${step.title}\nMilestone: ${step.milestoneProject}`).join('\n\n')}

---
Generated by SkillLens - "Know your gap. Build your path."
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-fadeIn">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[85vh] flex flex-col shadow-2xl border border-slate-200 overflow-hidden">
        
        {/* Modal Header */}
        <div className="p-5 bg-slate-900 text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center space-x-2">
            <FileText className="w-5 h-5 text-sky-400" />
            <h3 className="font-bold text-base sm:text-lg">Export Career Gap Report</h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto flex-1 space-y-4 text-xs sm:text-sm text-slate-700">
          <p className="text-slate-500 text-xs">
            Copy this structured Markdown summary to save in Notion, GitHub, or your study notes:
          </p>

          <pre className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-slate-800 font-mono text-xs overflow-x-auto whitespace-pre-wrap max-h-72">
            {markdownText}
          </pre>
        </div>

        {/* Modal Footer Actions */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-end space-x-3">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-medium text-slate-600 hover:text-slate-800 hover:bg-slate-200 transition"
          >
            Close
          </button>
          <button
            onClick={handleCopy}
            className="inline-flex items-center space-x-1.5 px-5 py-2 rounded-xl bg-sky-600 hover:bg-sky-500 text-white text-xs font-bold shadow-sm transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-300" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy Markdown Report</span>
              </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
};
